on:
  push:
    branches:
      - main
    paths:
      - randstring/**.go
      - randstring/go.mod
      - randstring/go.sum
    tags:
      - randstring/v*
  workflow_dispatch: {}

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Fetch dependencies
        run: |
          cd randstring
          go mod download
      - name: Run tests
        run: |
          cd randstring
          go test -v ./...
